#!/bin/bash
water=$WATER
stir=$STIR
water_dec=$(echo "ibase=water; $water" | bc)
stir_dec=$(echo "ibase=stir; $stir" | bc)
sum_dec=$(($water_dec + $stir_dec))
sum_bestchol=$(echo "obase=bestchol; $sum_dec" | bc)
echo "The sum of WATER ($water) and STIR ($stir) is $sum_bestchol in base bestchol."

